default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= Figaro.env.host %>
  database: <%= Figaro.env.database %>
  username: <%= Figaro.env.database_username %>
  password: <%= Figaro.env.database_password %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
